MONGODB_URL = "mongodb://127.0.0.1:27017"
MONGODB_COLLECTION = "chat_catch"
MAX_CONNECTIONS_COUNT = 10
MIN_CONNECTIONS_COUNT = 1
# API_PREFIX
# JWT_TOKEN_PREFIX - "token"
# SECRET_KEY
# ACCESS_TOKEN_EXPIRE_MINUTES
